# -*- coding: utf-8 -*-
__title__ = "Batch\nImport"
__doc__ = "Select multiple plan lines/curves, select a slab, and pick a JSON design file to import all tendons in a single batch."

import os
import math
import json
from pyrevit import forms, script
from Autodesk.Revit.DB import *
from Autodesk.Revit.UI.Selection import ObjectType

doc = __revit__.ActiveUIDocument.Document
uidoc = __revit__.ActiveUIDocument

METERS_TO_FEET = 3.28084
MM_TO_FEET = 0.00328084

def setup_tendonflow_parameters(doc):
    app = doc.Application
    orig_sp_path = app.SharedParametersFilename
    
    temp_file = os.path.join(os.getenv("TEMP"), "TendonFlowSharedParameters.txt")
    if not os.path.exists(temp_file):
        try:
            with open(temp_file, "w") as f:
                f.write("# Shared Parameters File generated by TendonFlow\r\n")
        except Exception:
            pass
            
    app.SharedParametersFilename = temp_file
    
    try:
        sp_file = app.OpenSharedParameterFile()
        if not sp_file:
            return
            
        group_name = "TendonFlow Design Data"
        group = sp_file.Groups.get_Item(group_name)
        if not group:
            group = sp_file.Groups.Create(group_name)
            
        params_to_create = [
            ("TF_TendonForce", "Prestressing Force applied to tendon (kN)", "number"),
            ("TF_DuctDiameter", "Outer diameter of the tendon duct", "length"),
            ("TF_CoverTop", "Top concrete cover thickness", "length"),
            ("TF_CoverBottom", "Bottom concrete cover thickness", "length"),
            ("TF_InflectionRatio", "Tendon curvature inflection point ratio", "number"),
            ("TF_SlabThickness", "Slab thickness at tendon location", "length"),
            ("TF_Support_0", "Elevation of Tendon at Start Support (above bottom of slab)", "length"),
            ("TF_Support_1", "Elevation of Tendon at Support 1 (above bottom of slab)", "length"),
            ("TF_Support_2", "Elevation of Tendon at Support 2 (above bottom of slab)", "length"),
            ("TF_Support_3", "Elevation of Tendon at End Support (above bottom of slab)", "length"),
            ("TF_LowPoint_1", "Elevation of Tendon at Span 1 Low Point (above bottom of slab)", "length"),
            ("TF_LowPoint_2", "Elevation of Tendon at Span 2 Low Point (above bottom of slab)", "length"),
            ("TF_LowPoint_3", "Elevation of Tendon at Span 3 Low Point (above bottom of slab)", "length"),
            ("TF_SpanLength_1", "Length of Span 1", "length"),
            ("TF_SpanLength_2", "Length of Span 2", "length"),
            ("TF_SpanLength_3", "Length of Span 3", "length"),
            ("TF_LineID", "UniqueID of the plan layout curve element", "text"),
            ("TF_SlabID", "UniqueID of the concrete slab floor element", "text")
        ]
        
        categories = app.Create.NewCategorySet()
        categories.Insert(doc.Settings.Categories.get_Item(BuiltInCategory.OST_GenericModel))
        binding = app.Create.NewInstanceBinding(categories)
        
        is_revit_2022_or_newer = hasattr(SpecTypeId, "String")
        
        t = Transaction(doc, "Setup TendonFlow Parameters")
        t.Start()
        
        for name, desc, p_type in params_to_create:
            definition = group.Definitions.get_Item(name)
            if not definition:
                if is_revit_2022_or_newer:
                    if p_type == "length":
                        spec = SpecTypeId.Length
                    elif p_type == "number":
                        spec = SpecTypeId.Number
                    else:
                        spec = SpecTypeId.String.Text
                    opt = ExternalDefinitionCreationOptions(name, spec)
                    definition = group.Definitions.Create(opt)
                else:
                    if p_type == "length":
                        pt = ParameterType.Length
                    elif p_type == "number":
                        pt = ParameterType.Number
                    else:
                        pt = ParameterType.Text
                    definition = group.Definitions.Create(name, pt)
            
            iterator = doc.ParameterBindings.ForwardIterator()
            already_bound = False
            while iterator.MoveNext():
                if iterator.Key.Name == name:
                    already_bound = True
                    break
            
            if not already_bound:
                doc.ParameterBindings.Insert(definition, binding, BuiltInParameterGroup.PG_DATA)
                
        t.Commit()
    except Exception:
        pass
    finally:
        if orig_sp_path:
            app.SharedParametersFilename = orig_sp_path

def set_param_value(elem, name, value, p_type):
    try:
        p = elem.LookupParameter(name)
        if p:
            if p.StorageType == StorageType.String:
                if p_type == "length":
                    p.Set("{} mm".format(value))
                else:
                    p.Set(str(value))
            elif p.StorageType == StorageType.Double:
                if p_type == "length":
                    p.Set(float(value) / 304.8)
                else:
                    p.Set(float(value))
            else:
                p.Set(str(value))
    except Exception:
        pass

def find_family_template():
    rvt_year = doc.Application.VersionNumber
    paths_to_check = [
        r"C:\ProgramData\Autodesk\RVT {}\Family Templates\English\Metric Generic Model.rft".format(rvt_year),
        r"C:\ProgramData\Autodesk\RVT {}\Family Templates\English-Imperial\Generic Model.rft".format(rvt_year),
        r"C:\ProgramData\Autodesk\RVT {}\Family Templates\English_I\Generic Model.rft".format(rvt_year)
    ]
    for p in paths_to_check:
        if os.path.exists(p):
            return p
            
    # Fallback search if not found in standard paths
    base_dir = r"C:\ProgramData\Autodesk\RVT {}".format(rvt_year)
    if os.path.exists(base_dir):
        for root, dirs, files in os.walk(base_dir):
            for file in files:
                if file.lower() in ["metric generic model.rft", "generic model.rft"]:
                    return os.path.join(root, file)
    return None

def create_tendon_geometry_element(doc, solid, line_id, slab_id, state, supports, low_points, span_lengths, slab_thickness_mm, import_data_id="TendonDuct"):
    t_proj = Transaction(doc, "Import Tendon Geometry")
    t_proj.Start()
    try:
        ds = DirectShape.CreateElement(doc, ElementId(BuiltInCategory.OST_GenericModel))
        ds.ApplicationId = "TendonFlow"
        ds.ApplicationDataId = import_data_id
        ds.SetShape([solid])
        
        set_param_values(ds, line_id, slab_id, state, supports, low_points, span_lengths, slab_thickness_mm)
        t_proj.Commit()
        return ds
    except Exception as ex:
        t_proj.RollBack()
        raise ex

def set_param_values(elem, line_id, slab_id, state, supports, low_points, span_lengths, slab_thickness_mm):
    set_param_value(elem, "TF_TendonForce", state.get('tendonForce', 1400.0), "number")
    set_param_value(elem, "TF_DuctDiameter", state.get('ductDiameter', 25.0), "length")
    set_param_value(elem, "TF_CoverTop", state.get('coverTop', 25.0), "length")
    set_param_value(elem, "TF_CoverBottom", state.get('coverBottom', 25.0), "length")
    set_param_value(elem, "TF_InflectionRatio", state.get('inflectionRatio', 0.1), "number")
    set_param_value(elem, "TF_SlabThickness", slab_thickness_mm, "length")
    
    for idx, val in enumerate(supports):
        set_param_value(elem, "TF_Support_{}".format(idx), val, "length")
    for idx in range(len(supports), 4):
        set_param_value(elem, "TF_Support_{}".format(idx), -1.0, "length")
        
    for idx, val in enumerate(low_points):
        y_val = val.get('y', 25.0) if isinstance(val, dict) else val
        set_param_value(elem, "TF_LowPoint_{}".format(idx + 1), y_val, "length")
    for idx in range(len(low_points) + 1, 4):
        set_param_value(elem, "TF_LowPoint_{}".format(idx), -1.0, "length")
        
    for idx, val in enumerate(span_lengths):
        set_param_value(elem, "TF_SpanLength_{}".format(idx + 1), val * 1000.0, "length")
    for idx in range(len(span_lengths), 3):
        set_param_value(elem, "TF_SpanLength_{}".format(idx + 1), -1.0, "length")
        
    set_param_value(elem, "TF_LineID", line_id, "text")
    set_param_value(elem, "TF_SlabID", slab_id, "text")

def evaluate_tendon_y(x_global, span_lengths, supports, low_points, inflection_ratio):
    accum_x = 0.0
    span_idx = -1
    local_x = 0.0
    
    for idx, L in enumerate(span_lengths):
        if accum_x <= x_global <= (accum_x + L + 0.0001):
            span_idx = idx
            local_x = x_global - accum_x
            break
        accum_x += L
        
    if span_idx == -1:
        span_idx = len(span_lengths) - 1
        local_x = span_lengths[span_idx]
        
    L = span_lengths[span_idx]
    yL = supports[span_idx] if span_idx < len(supports) else supports[-1]
    yR = supports[span_idx + 1] if (span_idx + 1) < len(supports) else supports[-1]
    
    lp = low_points[span_idx]
    xm = lp.get('xFract', 0.5) * L
    ym = lp.get('y', 25.0)
    a = inflection_ratio
    
    if local_x <= xm:
        X1 = xm
        Y1 = yL - ym
        b1 = max(0.05, min(0.95, (a * L) / X1))
        x_inf = b1 * X1
        a1_low = Y1 / ((1.0 - b1) * X1 * X1)
        a1_supp = Y1 / (b1 * X1 * X1)
        
        if local_x >= x_inf:
            return ym + a1_low * (xm - local_x) * (xm - local_x)
        else:
            return yL - a1_supp * local_x * local_x
    else:
        X2 = L - xm
        Y2 = yR - ym
        b2 = max(0.05, min(0.95, (a * L) / X2))
        x_inf = L - b2 * X2
        a2_low = Y2 / ((1.0 - b2) * X2 * X2)
        a2_supp = Y2 / (b2 * X2 * X2)
        
        if local_x <= x_inf:
            return ym + a2_low * (local_x - xm) * (local_x - xm)
        else:
            return yR - a2_supp * (L - local_x) * (L - local_x)

def create_swept_solid(path, radius):
    deriv = path.ComputeDerivatives(0.0, True)
    pt = deriv.Origin
    tangent = deriv.BasisX.Normalize()
    
    if abs(tangent.Z) < 0.999:
        u = tangent.CrossProduct(XYZ.BasisZ).Normalize()
    else:
        u = tangent.CrossProduct(XYZ.BasisX).Normalize()
    v = tangent.CrossProduct(u).Normalize()
    
    arc1 = Arc.Create(pt, radius, 0, math.pi, u, v)
    arc2 = Arc.Create(pt, radius, math.pi, 2 * math.pi, u, v)
    
    profile_loop = CurveLoop()
    profile_loop.Append(arc1)
    profile_loop.Append(arc2)
    
    profile_list = [profile_loop]
    sweep_path_loop = CurveLoop()
    sweep_path_loop.Append(path)
    
    return GeometryCreationUtilities.CreateSweptGeometry(
        sweep_path_loop,
        0,
        0.0,
        profile_list
    )

# --- Execution Workflow ---
try:
    # 1. Select Multiple Tendon Lines
    line_refs = uidoc.Selection.PickObjects(
        ObjectType.Element, 
        "Select multiple plan lines/curves for batch import, then click Finish in the top-left"
    )
    
    if line_refs:
        # 2. Select the Concrete Slab Floor (once)
        slab_ref = uidoc.Selection.PickObject(
            ObjectType.Element, 
            "Select the concrete slab floor element to contain all tendons"
        )
        slab_elem = doc.GetElement(slab_ref)
        if not isinstance(slab_elem, Floor):
            forms.alert("Selected element is not a Floor (Slab)!", title="Selection Error")
            script.exit()
            
        # 3. Pick the JSON Design File (once)
        json_file = forms.pick_file(file_ext="json", title="Select TendonFlow JSON Export File for Batch Import")
        if json_file:
            with open(json_file, 'r') as f:
                data = json.load(f)
                
            state = data.get('state', {})
            span_lengths = state.get('spanLengths', [])
            inflection_ratio = state.get('inflectionRatio', 0.1)
            selected_row_idx = state.get('selectedRowIdx', 0)
            cp_rows = state.get('controlPointsRows', [])
            
            if selected_row_idx >= len(cp_rows):
                forms.alert("No valid control point row found in JSON.", title="Error")
                script.exit()
                
            cp = cp_rows[selected_row_idx]
            supports = cp.get('supports', [])
            low_points = cp.get('lowPoints', [])
            
            # Calculate slab thickness and bottom elevation
            bbox = slab_elem.get_BoundingBox(None)
            slab_bottom_z_ft = bbox.Min.Z
            slab_top_z_ft = bbox.Max.Z
            slab_thickness_mm = (slab_top_z_ft - slab_bottom_z_ft) * 304.8
            
            # 4. Generate all tendons
            setup_tendonflow_parameters(doc)
            
            success_count = 0
            error_count = 0
            
            duct_diameter_mm = state.get("ductDiameter", 25.0)
            radius_ft = (duct_diameter_mm / 2.0) * MM_TO_FEET
            
            # Reusable math solver
            def eval_y(x_val):
                return evaluate_tendon_y(x_val, span_lengths, supports, low_points, inflection_ratio)
                
            for ref in line_refs:
                try:
                    line_elem = doc.GetElement(ref)
                    g_curve = None
                    if hasattr(line_elem, "GeometryCurve"):
                        g_curve = line_elem.GeometryCurve
                    elif isinstance(line_elem, CurveElement):
                        g_curve = line_elem.GeometryCurve
                        
                    if not g_curve:
                        error_count += 1
                        continue
                        
                    # Curve length in meters
                    curve_len_meters = g_curve.Length / METERS_TO_FEET
                    total_design_len = sum(span_lengths)
                    
                    # Determine curve direction in plan (left-to-right)
                    pt_start = g_curve.GetEndPoint(0)
                    pt_end = g_curve.GetEndPoint(1)
                    reverse_eval = False
                    if abs(pt_start.X - pt_end.X) > 0.001:
                        if pt_start.X > pt_end.X:
                            reverse_eval = True
                    else:
                        if pt_start.Y > pt_end.Y:
                            reverse_eval = True
                            
                    xyz_points = []
                    num_steps = 100
                    for step in range(num_steps + 1):
                        t = step / float(num_steps)
                        t_eval = (1.0 - t) if reverse_eval else t
                        pt = g_curve.Evaluate(t_eval, True)
                        
                        x_m = t * curve_len_meters
                        x_design = x_m * (total_design_len / curve_len_meters)
                        
                        z_mm = eval_y(x_design)
                        z_ft = z_mm * MM_TO_FEET
                        z_global_ft = slab_bottom_z_ft + z_ft
                        xyz_points.append(XYZ(pt.X, pt.Y, z_global_ft))
                        
                    draped_curve = HermiteSpline.Create(xyz_points, False)
                    duct_solid = create_swept_solid(draped_curve, radius_ft)
                    
                    ds = create_tendon_geometry_element(
                        doc, duct_solid, line_elem.UniqueId, slab_elem.UniqueId,
                        state, supports, low_points, span_lengths, slab_thickness_mm,
                        import_data_id="TendonDuctBatch"
                    )
                    
                    success_count += 1
                except Exception:
                    error_count += 1
            
            msg = "Batch Import Complete!\n\nSuccessfully created: {} tendon(s)".format(success_count)
            if error_count > 0:
                msg += "\nFailed to create: {} element(s)".format(error_count)
            forms.alert(msg, title="Batch Success")
            
except Exception as ex:
    forms.alert("Batch selection cancelled or failed: {}".format(ex), title="Cancelled")
